In [3]:
#Numpy
#veri madenciliği, veri analizi ve makine öğrenmesi
#tek boyutlu ve çok boyutlu array yapısı
#***Neden Numpy??***
#array yapısı, listelere göre oldukça az yer kaplar.
#arrayler elemanlarına erişmek listelere göre daha hızlıdır.
#Kolay ve hızlı kodlar ve fonksiyonlar


In [1]:
data_list = [1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(data_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [8]:
arr2 = np.array(data_list2)

In [9]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
arr3 =np.array([1,2,3])

In [13]:
arr3

array([1, 2, 3])

In [15]:
arr3[2]

3

In [16]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
arr2[2][2]

90

In [18]:
arr2[2,2]

90

In [19]:
np.arange(10,20) #10,20 arasındaki değerleri alır fakat 20 dahil değil

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [22]:
np.zeros(10) #10 tane 0 depolanır

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(4) #n tane değer depolar

array([1., 1., 1., 1.])

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
np.linspace(0,100,5)
#0 ile 100 arasını 5 eşit parçaya bölerek değerleri saklar

array([  0.,  25.,  50.,  75., 100.])

In [27]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [28]:
np.eye(6) #6,6 matrisi oluşturur

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
np.random.randint(0,10) #0 ile 10 arasında random değer atanır. 10 dahil değil

3

In [31]:
np.random.randint(10) #0 ile 10 arasında sayılır

8

In [32]:
np.random.randint(1,10,5) #1-10 arasında 5 tane değer oluşturur

array([8, 1, 2, 9, 3])

In [33]:
np.random.randn(5)#rand ran farklı olarak - değerlerde alır.

array([ 1.60007407, -0.54931638, -0.98331993,  0.54072386,  1.41257094])

In [35]:
np.random.rand(3)

array([0.81648515, 0.77992013, 0.1936041 ])

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.reshape(5,5) #tam olarak yerleşmesi gerekir. matris oluşturur

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
newArray = np.random.randint(1,100,10)

In [41]:
newArray

array([68, 52, 29, 48, 19, 46, 67, 91, 61, 26])

In [43]:
newArray.max() #array içindeki maks değer

91

In [44]:
newArray.min() #array içindeki min değer

19

In [45]:
newArray.sum() #değerlerin toplamını verir

507

In [47]:
newArray.mean() #array içindeki değerlerin ortalaması

50.7

In [48]:
newArray.argmax() #maks sayının indeksini verir

7

In [50]:
newArray.argmin() #min sayının indeksini verir

4

In [51]:
detArray = np.random.randint(1,100,25)

In [52]:
detArray

array([32, 64, 71, 73, 41, 64, 15, 32, 50, 97, 96,  4, 19, 67, 28, 18, 58,
        4, 76, 16, 40, 94, 52,  9, 41])

In [53]:
detArray=detArray.reshape(5,5)

In [54]:
detArray

array([[32, 64, 71, 73, 41],
       [64, 15, 32, 50, 97],
       [96,  4, 19, 67, 28],
       [18, 58,  4, 76, 16],
       [40, 94, 52,  9, 41]])

In [55]:
np.linalg.det(detArray) #içinde verilen değerin determinantı bulunur

2683800126.0000005

In [56]:
detArray2= np.array([[1,2],[3,4]])

In [57]:
detArray2

array([[1, 2],
       [3, 4]])

In [58]:
np.linalg.det(detArray2)

-2.0000000000000004

In [59]:
round(np.linalg.det(detArray2))

-2

In [60]:
#1. DERS TEKRARI

In [88]:
import numpy as np
array = np.array([1,2,3,4,5,6])
array2 = np.random.randint(1,10,6)
array3 = array + array2
print(array3.min())
print(array3.max())
print(array3.argmax())
print(array3.argmin())
print( array3.sum())
print(array3.mean())

5
13
5
1
51
8.5


In [89]:
array3.reshape(2,3)

array([[ 9,  5,  6],
       [ 7, 11, 13]])

In [93]:
#2. DERS

In [94]:
arr = np.arange(1,10)

In [95]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr[1]

2

In [98]:
arr[1:5] #1 ile 5. indekleri arasını alır

array([2, 3, 4, 5])

In [99]:
arr[:5]

array([1, 2, 3, 4, 5])

In [100]:
arr[::2]

array([1, 3, 5, 7, 9])

In [101]:
arr[:3]

array([1, 2, 3])

In [102]:
arr[:3]=25

In [103]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [104]:
arr = np.arange(1,10)

In [105]:
arr2=arr

In [106]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr2[:3]=100 #arr de değişir

In [108]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [109]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [110]:
arr = np.arange(1,10)

In [111]:
arr2= arr.copy()

In [112]:
arr2[:3] = 100 # arr2 değişir arr değişmez

In [113]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [114]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
newArray = np.arange(1,21)

In [116]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [117]:
newArray = newArray.reshape(5,4)

In [118]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [119]:
newArray[0,0]

1

In [120]:
#bütün satırların ilk iki değeri
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [122]:
newArray[:3,:3] #ilk 3 satırı al ve ilk 3 indeksi yazdır

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [123]:
newArray[:2,:] #ilk 2 satır bütün değerler

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
arr = np.arange(1,11)

In [128]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
arr >3 

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [130]:
boolArray = arr>3

In [131]:
boolArray

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [133]:
arr[boolArray] #false değerleri atarak değerleri gösterir

array([ 4,  5,  6,  7,  8,  9, 10])

In [134]:
arr[arr>5] #daha kolay yolu

array([ 6,  7,  8,  9, 10])

In [135]:
#2. DERS TEKRARI

In [143]:
liste = np.arange(11,31)

In [144]:
liste

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [145]:
liste = liste.reshape(4,5)

In [146]:
liste

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [147]:
liste[:,:2]

array([[11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [148]:
liste[:2,:3]

array([[11, 12, 13],
       [16, 17, 18]])

In [149]:
liste[::]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [150]:
liste[:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [151]:
liste[:1,:]

array([[11, 12, 13, 14, 15]])

In [152]:
boolList = liste >2

In [153]:
boolList

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [154]:
boolList[liste>20]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [155]:
liste[liste>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [156]:
#NUMPY ARRAYLERİN TEMEL OPERASYONLARI

In [174]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,3,4,5,6,7])

In [162]:
arr1 + arr2 #her bir eleman kendi içinde toplanır

array([12, 23, 34, 45, 56, 67])

In [163]:
arr1 - arr2

array([ 8, 17, 26, 35, 44, 53])

In [164]:
arr1 * arr2

array([ 20,  60, 120, 200, 300, 420])

In [165]:
arr1 / arr2

array([5.        , 6.66666667, 7.5       , 8.        , 8.33333333,
       8.57142857])

In [166]:
arr1 +10 

array([20, 30, 40, 50, 60, 70])

In [167]:
arr2 -1

array([1, 2, 3, 4, 5, 6])

In [178]:
arr1

array([10, 20, 30, 40, 50, 60])

In [179]:
np.sqrt(arr1) #her bir elemanın karekökü alınır

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [181]:
#*******************ÖDEV#*******************

In [182]:
import numpy as np

In [185]:
arr1 = np.ones(5)

In [186]:
arr1

array([1., 1., 1., 1., 1.])

In [187]:
arr0 =np.zeros(5)

In [188]:
arr0

array([0., 0., 0., 0., 0.])

In [189]:
arr = np.arange(0,100,2)

In [190]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [194]:
arr10 = np.ones(5)*10

In [195]:
arr10

array([10., 10., 10., 10., 10.])

In [196]:
arr = np.arange(1,17)

In [197]:
arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [198]:
arr = arr.reshape(4,4)

In [199]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [202]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [203]:
arr1 = np.random.randint(0,5,1)

In [204]:
arr1

array([3])

In [206]:
np.random.randn(25).reshape(5,5)

array([[ 0.66849193, -0.09672231, -0.26121751, -1.04770913, -0.11425857],
       [ 0.84622557, -2.03413003,  0.58096986,  0.03491819, -0.09776554],
       [ 1.15567733,  1.08690756, -0.20877012,  0.84259816,  0.84016045],
       [ 1.63620174,  1.68866309, -0.49598453,  1.58026376, -1.31803342],
       [ 2.03912587, -2.67430809,  0.40717472, -1.24014258, -0.40178136]])

In [207]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [208]:
arr  = np.arange(1,101).reshape(10,10)

In [209]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [210]:
arr[arr>40]

array([ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [211]:
arr[arr>64]

array([ 65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [212]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [213]:
arr[:6,:6]

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36],
       [41, 42, 43, 44, 45, 46],
       [51, 52, 53, 54, 55, 56]])

In [214]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [215]:
arr[:3,1]

array([ 2, 12, 22])

In [225]:
arr[0:3,1:2]

array([[ 2],
       [12],
       [22]])

In [226]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [227]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [228]:
arr1

array([[3, 0, 4],
       [3, 3, 0],
       [1, 1, 0]])

In [229]:
arr2

array([[1, 2, 4],
       [2, 4, 4],
       [1, 1, 1]])

In [230]:
arr1 + arr2

array([[4, 2, 8],
       [5, 7, 4],
       [2, 2, 1]])

In [231]:
arr1*arr2

array([[ 3,  0, 16],
       [ 6, 12,  0],
       [ 1,  1,  0]])

In [232]:
arr1.mean()

1.6666666666666667

In [234]:
arr1.sum()

15

In [235]:
arr1.mean()+arr2.mean()

3.8888888888888893